[package]
name = "stdx"
version = "0.118.0-rc"
authors = ["Brian Anderson <banderson@mozilla.com>"]
description = "The missing batteries of Rust"
license = "MIT/Apache-2.0"

[dependencies]

# If you update these also update all the versions in README.md
# Note: crates are presented in alphabetical order.

bitflags = "0.9.1"
byteorder = "1.0.0"
